# Generated by Django 4.2.24 on 2025-09-08 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="设置键", max_length=100, unique=True),
                ),
                ("value", models.TextField(help_text="设置值")),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("ai", "AI配置"),
                            ("system", "系统配置"),
                            ("security", "安全配置"),
                            ("ui", "界面配置"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="设置描述")),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, help_text="是否加密存储"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("ai_generation", "AI内容生成"),
                            ("ai_query", "AI查询"),
                            ("system", "系统调用"),
                            ("error", "错误日志"),
                        ],
                        default="ai_generation",
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        blank=True, help_text="使用的AI模型", max_length=50
                    ),
                ),
                ("request_data", models.JSONField(default=dict, help_text="请求数据")),
                ("response_data", models.JSONField(default=dict, help_text="响应数据")),
                ("status_code", models.IntegerField(default=200, help_text="状态码")),
                ("duration", models.FloatField(default=0.0, help_text="耗时（秒）")),
                (
                    "tokens_used",
                    models.IntegerField(default=0, help_text="使用的token数"),
                ),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP地址", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="用户代理")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API日志",
                "verbose_name_plural": "API日志",
                "db_table": "api_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(help_text="模型ID", max_length=50, unique=True),
                ),
                (
                    "model_name",
                    models.CharField(help_text="模型显示名称", max_length=100),
                ),
                ("provider", models.CharField(help_text="提供商", max_length=50)),
                ("api_key", models.TextField(help_text="API密钥（加密存储）")),
                ("base_url", models.URLField(help_text="API基础URL")),
                (
                    "model_version",
                    models.CharField(default="", help_text="模型版本", max_length=50),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=2000, help_text="最大token数"),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, help_text="默认温度参数"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                (
                    "is_available",
                    models.BooleanField(default=False, help_text="是否可用"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, help_text="最后检查时间", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                (
                    "supported_content_types",
                    models.JSONField(default=list, help_text="支持的内容类型"),
                ),
                (
                    "config_data",
                    models.JSONField(default=dict, help_text="额外配置数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ai_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI模型配置",
                "verbose_name_plural": "AI模型配置",
                "db_table": "ai_model_configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
