# Generated by Django 4.2.24 on 2025-09-10 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('glm', '智谱AI')], help_text='提供商', max_length=20, unique=True)),
                ('api_key', models.TextField(help_text='API密钥')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('last_tested', models.DateTimeField(blank=True, help_text='最后测试时间', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='是否有效')),
                ('error_message', models.TextField(blank=True, help_text='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key配置',
                'verbose_name_plural': 'API Key配置',
                'db_table': 'api_key_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
