# Generated by Django 4.2.24 on 2025-09-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="文件大小（字节）", null=True
            ),
        ),
    ]
