# Generated by Django 4.2.24 on 2025-09-11 05:05

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='vector_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
