# Generated by Django 4.2.24 on 2025-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_document_vector_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(choices=[('general', '通用'), ('legal', '法律'), ('education', '教育'), ('healthcare', '医疗健康'), ('finance', '金融'), ('technology', '技术'), ('business', '商业'), ('science', '科学'), ('humanities', '人文社科'), ('engineering', '工程'), ('arts', '艺术设计'), ('other', '其他')], default='general', max_length=50),
        ),
    ]
