# Generated by Django 4.2.24 on 2025-11-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge", "0004_alter_knowledgebase_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("SUCCEEDED", "成功"),
                            ("FAILED", "失败"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("total_documents", models.PositiveIntegerField(default=0)),
                ("created_documents", models.PositiveIntegerField(default=0)),
                ("vectorized_documents", models.PositiveIntegerField(default=0)),
                ("skipped_documents", models.PositiveIntegerField(default=0)),
                ("skipped_samples", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_import_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
