# Generated by Django 4.2.24 on 2025-09-05 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qarecord",
            options={
                "ordering": ["session", "message_order"],
                "verbose_name": "问答记录",
                "verbose_name_plural": "问答记录",
            },
        ),
        migrations.AddField(
            model_name="qarecord",
            name="message_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="qarecord",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("user", "用户消息"),
                    ("assistant", "助手回复"),
                    ("system", "系统消息"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="qarecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天会话",
                "verbose_name_plural": "聊天会话",
                "db_table": "chat_sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddField(
            model_name="qarecord",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatsession",
            ),
        ),
    ]
